version: "4"

services:
  frontend:
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - ./mental-health-saas-front:/usr/src/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"

  backend:
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - ./mental-health-backend:/usr/src/app
    environment:
      DATABASE_URL: ${DATABASE_URL} 
    command: sh -c "npm install && npm run start"
    ports:
      - "8000:8000" 
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data:
