version: "3.8"
services:
  frontend:
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - ./mental-health-saas-front:/usr/src/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

  backend:
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - ./mental-health-backend:/usr/src/app
    environment:
      DATABASE_URL: "${MONGODB_URL}"
    command: sh -c "npm install && npx prisma generate && npm run start"
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}" 
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo-keyfile:/data/mongo-keyfile:ro
      - mongo_data:/data/db
    command: ["mongod", "--replSet", "rs0", "--keyFile", "/data/mongo-keyfile"]
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"

  mongo_setup:
    image: mongo:latest
    depends_on:
      - mongo
    command: >
      sh -c "
      sleep 10 &&
        mongosh --host mongo --username root --password prisma --eval 'rs.initiate({_id: \"rs0\", members: [{ _id: 0, host: \"mongo:27017\" }]})'
      "

  adminmongo:
    image: mrvautin/adminmongo
    container_name: adminmongo
    environment:
      - HOST=0.0.0.0
      - PORT=1234 
    ports:
      - "1234:1234"
    volumes:
      - adminmongo-data:/app
    depends_on:
      - mongo
    command: >
      sh -c "
      echo '{\"mongo\": {\"connectionString\": \"mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/?authSource=admin\"}}' > /app/config.json &&
      node app"



volumes:
  mongo_data:
  adminmongo-data:

