name: CI/CD Pipeline

on:
  push:
    branches:
      - main    
  pull_request:
    branches:
      - main   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v2

      - name: Installer Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'    
      - name: Installer les dépendances
        run: |
          cd backend
          npm install
          cd ../frontend
          npm install

      - name: Lancer les tests
        run: |
          cd backend
          npm run test
          cd ../frontend
          npm run test

      - name: Construire le frontend
        run: |
          cd frontend
          npm run build

      - name: Déployer (optionnel)
        run: |
          # Ajoute tes commandes de déploiement ici, par exemple pour AWS ou autre
          echo "Déploiement en cours..."
