name: CI/CD Pipeline

on:
  push:
    branches:
      - main    
  pull_request:
    branches:
      - main   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v2

      - name: Installer Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'    
      - name: Installer les dépendances
        run: |
          cd mental-health-backend
          npm install
          cd ../mental-health-saas-front
          npm install

      